### ISSUE TITLE
Extract assets error

### ISSUE THREAD

**Issue by Gaelcraft** [AloXado320/sm64ex-alo#26]
I am trying to compile it for windows but i get this error

$ make
extracting actors/amp/amp_body.rgba16.png
Traceback (most recent call last):
  File "/home/HyperGDude/sm64ex-alo/extract_assets.py", line 290, in <module>
    main()
  File "/home/HyperGDude/sm64ex-alo/extract_assets.py", line 246, in main
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: './tools/n64graphics'
Makefile:427: *** Failed to extract assets from US ROM.  Stop.

Windows 10 MinGW64

**Comment by Gaelcraft** [comment]
I already solved it but now I have problems with this 
make -j4 TARGET_SWITCH=1
Building tools...
Building game...
Converting to M64: build/us_nx/sound/sequences/00_sound_player.o -> build/us_nx/sound/sequences/00_sound_player.m64
C:\msys64\mingw64\bin\objcopy.exe: Unable to recognize the format of the input file `build/us_nx/sound/sequences/00_sound_player.o'
Applying Windows Icon ->
make: aarch64-none-elf-windres: No such file or directory
make: *** [Makefile:1612: build/us_nx/platform/win/info.o] Error 127
make: *** Waiting for unfinished jobs....
Compiling: lib/src/alBnkfNew.c -> build/us_nx/lib/src/alBnkfNew.o
make: *** [Makefile:1540: build/us_nx/sound/sequences/00_sound_player.m64] Error 1
Compiling: lib/src/guLookAtRef.c -> build/us_nx/lib/src/guLookAtRef.

**Comment by AloXado320** [comment]
Fixed in https://github.com/AloXado320/sm64ex-alo/commit/b9283d080d8f82befe3917a916843cbfb1399411
