### ISSUE TITLE
Cannot Compile on LInux

### ISSUE THREAD

**Issue by DraeTheHedgehog** [AloXado320/sm64ex-alo#39]
It compiled perfectly fine with the commit version from last week but does not compile with latest commit. I'm using the latest version of Linux Mint (21.1 Vera)

Error Message:

drae@DR43-L4PT0P:~/sm64ex-alo$ make
Traceback (most recent call last):
  File "/home/drae/sm64ex-alo/extract_assets.py", line 299, in <module>
    main() if __name__ == "__main__" else None
  File "/home/drae/sm64ex-alo/extract_assets.py", line 211, in main
    image = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: './tools/sm64tools/mio0'
Makefile:404: *** Failed to extract assets from US ROM.  Stop.

You can recreate this by getting any official SM64 rom and naming it accordingly to the rom names on the original decomp github repo I've tried it with all the official SM64 roms (US, EU, JP, and Shindou) and none work.

**Comment by AloXado320** [comment]
Made a mistake on the sm64tools folder that included binaries, should be fixed now.
